import { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { FileText, MessageSquare, Sparkles, Map, BriefcaseBusiness, ChevronRight, Check, ArrowUpRight, LoaderCircle } from 'lucide-react'
import './styles.css'

type Page = 'Resume Checker' | 'Interview' | 'Skill Gap' | 'Roadmap' | 'Internships'
const nav: { page: Page, icon: any }[] = [{ page: 'Resume Checker', icon: FileText }, { page: 'Interview', icon: MessageSquare }, { page: 'Skill Gap', icon: Sparkles }, { page: 'Roadmap', icon: Map }, { page: 'Internships', icon: BriefcaseBusiness }]
const roles = ['Frontend Developer', 'Data Analyst', 'Product Designer']
const internships = [
  ['Frontend Developer','React Intern','Luma Labs',['React','TypeScript','CSS'],'Remote'],['Data Analyst','Data Insights Intern','Pivota',['SQL','Excel','Tableau'],'Bengaluru'],['Frontend Developer','Web Engineering Intern','Nimble',['JavaScript','Git','REST APIs'],'Remote'],['Product Designer','Product Design Intern','Orbit',['Figma','User Research','Prototyping'],'Mumbai'],['Data Analyst','Business Analytics Intern','BrightPath',['Python','SQL','Statistics'],'Remote'],['Frontend Developer','UI Developer Intern','Aperture',['HTML/CSS','React','Testing'],'Delhi'],['Product Designer','UX Research Intern','Muse',['User Research','UX Writing','Figma'],'Remote'],['Data Analyst','Marketing Data Intern','Northstar',['Excel','Data Visualization','Communication'],'Pune'],['Frontend Developer','Design Systems Intern','Studiowork',['TypeScript','React','Figma'],'Remote']
]
const demoResume = `Aarav Sharma | Frontend Developer\nBuilt responsive React interfaces for a campus events platform used by 800 students.\nSkills: JavaScript, React, HTML, CSS, Git\nProjects: Designed and deployed a task tracker using REST APIs.`
async function api(path: string, body: object) { const r = await fetch('/api/' + path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); return r.json() }

function App() {
  const [page, setPage] = useState<Page>('Resume Checker'); const [role, setRole] = useState(roles[0]); const [resume, setResume] = useState(demoResume); const [skills, setSkills] = useState('JavaScript, React, HTML/CSS, Git'); const [gap, setGap] = useState<any>(null)
  return <div className="min-h-screen bg-cream text-ink"><aside className="sidebar"><div className="brand"><span className="brand-mark">A</span><span>career<span>•</span>ai</span></div><div className="nav-label">CAREER TOOLS</div>{nav.map(({page: p, icon: Icon}) => <button onClick={() => setPage(p)} className={'nav-item '+(page===p?'active':'')} key={p}><Icon size={18}/>{p}</button>)}<div className="side-bottom"><div className="avatar">AS</div><div><b>Aarav Sharma</b><small>Job seeker</small></div></div></aside><main><header><div><p className="eyebrow">YOUR CAREER DASHBOARD</p><h1>{page}</h1></div><div className="ready"><span></span> Profile 68% ready</div></header>
    {page === 'Resume Checker' && <Resume resume={resume} setResume={setResume}/>} 
    {page === 'Interview' && <Interview role={role} setRole={setRole}/>} 
    {page === 'Skill Gap' && <SkillGap role={role} setRole={setRole} skills={skills} setSkills={setSkills} gap={gap} setGap={setGap}/>} 
    {page === 'Roadmap' && <Roadmap role={role} gap={gap} onNeedGap={() => setPage('Skill Gap')}/>} 
    {page === 'Internships' && <Internships role={role} skills={skills}/>} 
  </main></div>
}
function RoleSelect({role,setRole}:{role:string,setRole:(r:string)=>void}) { return <select value={role} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option key={r}>{r}</option>)}</select> }
function Resume({resume,setResume}:{resume:string,setResume:(x:string)=>void}) { const [result,setResult]=useState<any>(null); const [busy,setBusy]=useState(false); const go=async()=>{setBusy(true);setResult(await api('resume-check',{resume}));setBusy(false)};return <section className="grid two"><div className="card"><p className="section-kicker">PASTE YOUR RESUME</p><h2>Let your experience speak clearly.</h2><textarea value={resume} onChange={e=>setResume(e.target.value)} /><button className="primary" onClick={go} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Sparkles size={18}/>} Analyze with AI <ChevronRight size={16}/></button></div><div className="card result-card">{result?<><div className="score"><div><span>{result.score}</span><small>/100</small></div><p>ATS health score</p></div><div className="score-bar"><i style={{width:result.score+'%'}}/></div><h3>What to improve</h3><ul className="suggestions">{result.suggestions.map((s:string,i:number)=><li key={i}><span>{i+1}</span>{s}</li>)}</ul></>:<Empty icon={<FileText/>} text="Your ATS feedback will appear here."/>}</div></section> }
function Interview({role,setRole}:{role:string,setRole:(x:string)=>void}) { const [history,setHistory]=useState<any[]>([]);const [question,setQuestion]=useState('Ready to practise? Choose a role and begin when you are ready.');const [answer,setAnswer]=useState('');const [feedback,setFeedback]=useState('');const [busy,setBusy]=useState(false);const send=async()=>{setBusy(true);const data=await api('interview',{role,answer,history}); if(answer) setHistory(h=>[...h,{answer,question,feedback:data.feedback}]); setFeedback(data.feedback);setQuestion(data.question);setAnswer('');setBusy(false)};return <section className="interview-wrap"><div className="toolbar"><div><p className="section-kicker">AI INTERVIEW COACH</p><h2>Practice with intent</h2></div><RoleSelect role={role} setRole={setRole}/></div><div className="chat card"><div className="coach"><div className="bot">✦</div><div><small>CAREER COACH</small><p>{question}</p></div></div>{history.map((m,i)=><div key={i}><div className="user-msg">{m.answer}</div><div className="feedback"><b>Coach feedback</b>{m.feedback}</div></div>)}<div className="answer"><textarea placeholder="Type your answer..." value={answer} onChange={e=>setAnswer(e.target.value)}/><button className="primary" onClick={send} disabled={busy}>{busy?'Thinking...':answer?'Send answer':'Start interview'} <ArrowUpRight size={16}/></button></div></div></section> }
function SkillGap({role,setRole,skills,setSkills,gap,setGap}:any) { const go=async()=>setGap(await api('skill-gap',{role,skills:skills.split(',').map((s:string)=>s.trim())})); return <section><div className="card skill-input"><div><p className="section-kicker">SKILL INVENTORY</p><h2>Find your next edge.</h2><div className="form-row"><RoleSelect role={role} setRole={setRole}/><input value={skills} onChange={e=>setSkills(e.target.value)} placeholder="Your skills, comma separated"/></div></div><button className="primary" onClick={go}>Find gaps <ChevronRight size={16}/></button></div>{gap&&<div className="grid two gap-results"><div className="card"><p className="section-kicker">YOU HAVE</p><h3>{gap.have.length} of {gap.required.length} core skills</h3><div className="pill-list green">{gap.have.map((s:string)=><span key={s}><Check size={14}/>{s}</span>)}</div></div><div className="card"><p className="section-kicker">TO FOCUS ON</p><h3>{gap.missing.length} growth opportunities</h3><div className="pill-list amber">{gap.missing.map((s:string)=><span key={s}>+ {s}</span>)}</div></div></div>}</section> }
function Roadmap({role,gap,onNeedGap}:any) { const [roadmap,setRoadmap]=useState<any>(null);const [busy,setBusy]=useState(false);const go=async()=>{setBusy(true);setRoadmap(await api('roadmap',{role,missing:gap.missing}));setBusy(false)}; if(!gap) return <div className="card empty-large"><Empty icon={<Map/>} text="First run a skill gap analysis so we can make your plan personal."/><button className="primary" onClick={onNeedGap}>Go to skill gap</button></div>;return <section><div className="toolbar"><div><p className="section-kicker">PERSONALIZED PLAN</p><h2>Your four-week sprint</h2></div><button className="primary" onClick={go} disabled={busy}>{busy?'Building...':'Generate roadmap'} <Sparkles size={16}/></button></div>{roadmap&&<div className="timeline">{roadmap.weeks.map((w:any)=><article className="card week" key={w.week}><div className="weeknum">{String(w.week).padStart(2,'0')}</div><div><small>WEEK {w.week}</small><h3>{w.title}</h3>{w.tasks.map((t:string)=><p key={t}><span className="checkbox"/> {t}</p>)}</div></article>)}</div>}</section> }
function Internships({role,skills}:{role:string,skills:string}) { const [filter,setFilter]=useState(''); const data=internships.filter(x=>x[0]===role && (!filter || (x[4] as string[]).some(s=>s.toLowerCase().includes(filter.toLowerCase()))));return <section><div className="toolbar"><div><p className="section-kicker">CURATED FOR YOU</p><h2>Internships worth applying to</h2></div><div className="filters"><select value={role} disabled><option>{role}</option></select><input placeholder="Filter by skill" value={filter} onChange={e=>setFilter(e.target.value)}/></div></div><div className="intern-grid">{data.map((x:any)=><article className="card internship" key={x[1]}><div className="company-mark">{x[2][0]}</div><small>{x[2]} · {x[5]}</small><h3>{x[1]}</h3><div className="tags">{x[4].map((s:string)=><span key={s}>{s}</span>)}</div><button>View opportunity <ArrowUpRight size={15}/></button></article>)}</div></section> }
function Empty({icon,text}:{icon:any,text:string}) {return <div className="empty">{icon}<p>{text}</p></div>};createRoot(document.getElementById('root')!).render(<App />)
